### PR TITLE
CLI #75 

### PR DESCRIPTION
**Pull request by amedeiros**
First pass at the CLI.

### CODE REVIEW

**Comment by reidmorrison** [comment]
Awesome work.

I am a little nervous with use `--config` to generate a new config when many people may assume that it should be the existing config file. I.e. They would end up generating a new config file by accident when they want to encrypt something.

How about  `--generate` to reduce the above risk?

Instead of storing the command line values in an options hash, how about using instance variables?
For example: https://github.com/rocketjob/rocketjob/blob/master/lib/rocket_job/cli.rb

**Comment by amedeiros** [comment]
All sounds good to me.

**Comment by reidmorrison** [comment]
@amedeiros I have been working on the CLI for Symmetric Encryption v4. Below is the output from the help:

~~~
Symmetric Encryption v4.0.0.alpha1

symmetric-encryption [options]
    -e, --encrypt [FILE_NAME]        Encrypt a file, or read from stdin if no file name is supplied.
    -d, --decrypt [FILE_NAME]        Decrypt a file, or read from stdin if no file name is supplied.
    -o, --output FILE_NAME           Write encrypted or decrypted file to this file, otherwise output goes to stdout.
    -P, --prompt                     When encrypting or decrypting, prompt for a string encrypt or decrypt.
    -z, --compress                   Compress encrypted output file.
    -E, --env ENVIRONMENT            Environment to use in the config file. Default: RACK_ENV || RAILS_ENV || 'development'
    -c, --config CONFIG_FILE_PATH    File name & path to the Symmetric Encryption configuration file. Default: config/symmetric-encryption.yml
    -r, --re-encrypt PATTERN         ReEncrypt all files matching the pattern. Default: "**/*.yml"
    -n, --new-password [SIZE]        Generate a new random password using only characters that are URL-safe base64. Default size is 22.
    -g, --generate                   Generate a new configuration file and encryption keys for every environment.
    -K, --key-path KEY_PATH          Output path in which to write generated key files. Default: /etc/symmetric-encryption
    -a, --app-name NAME              Application name to use when generating a new configuration. Default: symmetric-encryption
    -S, --envs ENVIRONMENTS          Comma separated list of environments for which to generate the config file. Default: development,test,release,production
    -C, --cipher-name NAME           Name of the cipher to use when generating a new config file, or when rotating keys. Default: aes-256-cbc
    -H, --heroku                     Target Heroku when generating a new config file, or when creating news keys.
    -T, --environment                Store the encrypted key in an environment variable when generating a new config file, instead of using a file store.
    -R, --rotate-keys                Generates a new encryption key version, encryption key files, and updates symmetric-encryption.yml.
    -D, --rolling-deploy             During key rotation, support a rolling deploy by placing the new key second in the list so that it is not activated yet.
    -V, --key-version NUMBER         Encryption key version to use when encrypting or re-encrypting. Default: (Current global version).
    -L, --ciphers                    List available OpenSSL ciphers.
    -v, --version                    Display Symmetric Encryption version.
    -h, --help                       Prints this help.
~~~

Do you think these options make sense? Any changes or suggestions?

Going to keep v4 around in beta for a while so that we can change any of these options as needed before locking them down.

It uses a completely different strategy to generate the config file and the encrypted keys.

Some examples to use the CLI: https://rocketjob.github.io/symmetric-encryption/cli

Early docs on the new config and key generation mechanism: https://rocketjob.github.io/symmetric-encryption/configuration.html

**Comment by amedeiros** [comment]
Looks good!

**Pull request merged**
